function TaskJacobian = g_Constraint_Jacobian(in1)
%G_CONSTRAINT_JACOBIAN
%    TASKJACOBIAN = G_CONSTRAINT_JACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Mar-2021 14:55:41

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q1);
t3 = q1+q2;
t4 = q3+t3;
t5 = sin(t3);
t6 = sin(t4);
t7 = -t5;
t8 = t5./2.0;
t9 = -t6;
t10 = -t8;
t11 = t6./2.0;
t12 = -t11;
TaskJacobian = reshape([t2.*(-1.0./2.0)+t10+t12,-t2+t7+t9,t10+t12,t7+t9,t12,t9],[2,3]);
