function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Mar-2021 14:50:05

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = q2+q3;
t5 = cos(t4);
t6 = t3.*(5.0./2.0);
t7 = t3.*(5.0./4.0);
t8 = t2.*(1.5e+1./4.0);
t9 = t5.*(5.0./4.0);
t10 = t7+2.5e+1./2.4e+1;
t11 = t9+t10;
t12 = t6+t8+t9+5.5e+1./1.2e+1;
H = reshape([t2.*(1.5e+1./2.0)+t5.*(5.0./2.0)+t6+8.5e+1./8.0,t12,t11,t12,t6+5.5e+1./1.2e+1,t10,t11,t10,2.5e+1./2.4e+1],[3,3]);
