function TaskJacobian_derivative = g_InverseKinematics_TaskJacobian_derivative(in1,in2)
%G_INVERSEKINEMATICS_TASKJACOBIAN_DERIVATIVE
%    TASKJACOBIAN_DERIVATIVE = G_INVERSEKINEMATICS_TASKJACOBIAN_DERIVATIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Mar-2021 14:55:43

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = cos(t4);
t6 = t3./2.0;
t7 = t5./2.0;
t9 = t5.*v3.*(-1.0./2.0);
t8 = t7.*v3;
t10 = t6+t7;
t11 = t10.*v2;
t12 = -t11;
TaskJacobian_derivative = reshape([0.0,0.0,t9+t12-v1.*(t10+cos(q1)./2.0),0.0,0.0,t9+t12-t10.*v1,0.0,0.0,t5.*(v1+v2+v3).*(-1.0./2.0)],[3,3]);
