%%

DrawRobot_function = SRD_DrawRobot_get_function('DrawRobot_Type', 'STL', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', [], ...
    'Function_Type', 'DrawGivenPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'Chain', [], ...
    'FileName_visuals_config', 'datafile_visuals_config.mat'); %use default visuals

% 
% 
% Parser.addOptional('DrawRobot_Type', 'Default'); %'Default' or 'STL' or 'Custom'
% Parser.addOptional('DrawRobot_Custom_handle', []); 
% Parser.addOptional('Function_Type', 'DrawGivenPosition'); %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
% Parser.addOptional('FileName_visuals_config', 'datafile_visuals_config.mat'); 
% Parser.addOptional('Chain', []);


SRD__animate__vanilla('Handler_Simulation', Handler_Simulation, ...
    'Handler_Logger', Handler_State_Logger_vanilla, ...
    'AnimationTimeLog', 0:10*dt:(tf-dt), ...
    'DrawRobot_function', DrawRobot_function, ...
    'NewFigure', true, ...
    'FigureName', 'Animation', ...
    'FileName_visuals_config', 'datafile_visuals_config.mat');