clear ; close ;

%Get initial positionSRD_get_handler__IK_solution__interp1
InitialPosition = SRD_get('InitialPosition');
Handler_IK_Model = SRD_get('Handler_IK_Model');
Task = Handler_IK_Model.get_Task;
IC_Task = Task(InitialPosition);
% Handler_dynamics = SRD_get("Handler_dynamics_generalized_coordinates_model");


TimeTable = linspace(0,2,50);


Goal_task = [0.5;...
             IC_Task(2);...
             -0.2];
         
  
Obs_pose  = [[0.33;IC_Task(2);-0.30],[0.35;IC_Task(2);-0.27],[0.4;IC_Task(2);-0.25]];     
Task_params = [Goal_task,Obs_pose];
Wieght = [2,0.2];
         
% [dist,diff_dist]= get_distance(FK_fun,q,xb);


IC_Task = Handler_IK_Model.get_Task(InitialPosition);


[IK_Table,V_Table] = SRD_InverseKinematics_GenerateTable_ode_m(...
    'Task_params',Task_params,...
    'Wieght',Wieght,...
    'Handler_IK_Model', Handler_IK_Model, ...
    'InitialGuess', InitialPosition, ...
    'method', @SRD_InversePositionProblemSolver_Ode_Dynamics,...
    'TimeTable', TimeTable);

SRD_InverseKinematics_GenerateTable_tester_ode(...
    'Handler_IK_Model', Handler_IK_Model, ...
    'TimeTable', TimeTable, ...
    'IK_Table', IK_Table,...
    'V_Table', V_Table);

Handler_IK_Solution = SRD_get_handler__IK_solution__interp1_ode(...
    'Handler_IK_Model_name', 'Handler_IK_Model', ...
    'Handler_IK_task_name', 'Handler_IK_task', ...
    'IK_Table', IK_Table, ...
    'V_Table', V_Table, ...
    'TimeTable', TimeTable, ...
    'method', 'linear');

SRD_save(Handler_IK_Solution, 'Handler_IK_Solution_Ikdyn_m')


disp("goal pose: "+Goal_task);
disp("desired: "+Handler_IK_Model.get_Task(IK_Table(end,:)'));




%%




tf = TimeTable(end);
dt = 0.1;
Handler_Simulation = SRD_get_handler__Simulation(...
    'TimeLog',TimeTable );
DrawRobot_function = SRD_DrawRobot_get_function('DrawRobot_Type', 'STL', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', [], ...
    'Function_Type', 'DrawGivenPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'Chain', [], ...
    'FileName_visuals_config', 'datafile_visuals_config.mat'); %use default visuals
SRD__animate__position_m('Handler_Simulation', Handler_Simulation, ...
    'Handler_Logger_position', Handler_IK_Solution, ...
    'AnimationTimeLog', 0:10*dt:(tf-dt), ...
    'DrawRobot_function', DrawRobot_function, ...
    'Handler_IK_Model', Handler_IK_Model,...
    'Task_params',Task_params,...
    'IK_Table', IK_Table,...
    'NewFigure', true, ...
    'FigureName', 'Animation', ...
    'FileName_visuals_config', []);


