function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Mar-2021 22:10:56

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t4.*9.723699203978239e-1;
t9 = t7.*9.723699203978239e-1;
t10 = t4.*2.334453638552917e-1;
t11 = t7.*2.334453638552917e-1;
t12 = -t9;
t13 = t8+t11;
t14 = t10+t12;
Task = [t6.*(-1.0./5.0)+(t3.*t13)./5.0-(t6.*(t9-t10))./5.0+1.83e+2./1.0e+3;t2.*(-8.505e-2)+(t3.*t5)./5.0+(t5.*t6.*t13)./5.0+(t3.*t5.*(t9-t10))./5.0-4.7e+1./1.0e+3;t5.*(-8.505e-2)-(t2.*t3)./5.0-(t2.*t6.*t13)./5.0-(t2.*t3.*(t9-t10))./5.0];
